### ISSUE TITLE
How do you get the XML feed?

### ISSUE THREAD

**Issue by odarbelaeze** [jonbellah/jonbellah.com#2]
Hi I got a similar stack and would like to build myself a feed, could you share your magic?

**Comment by jonbellah** [comment]
Hi, thanks for checking out the site.

I'm using [gatsby-plugin-feed](https://www.gatsbyjs.org/packages/gatsby-plugin-feed/) to generate the feed. You can find my configuration in my `gatsby-config.js` file.
