### ISSUE TITLE
I have Lot's of images...Is this a good script for lot's of images?

### ISSUE THREAD

**Issue by Helpmetoday** [jonbellah/jonbellah.com#4]
Hey John,
Before I make final what you have sent me in your last email, (and I Thank You for it) do you think it will be ok (won't slow down my page loading time or other issues) if I have nearly 200 images (197 to be exact) that I will have to setup in your php switch statement to do the links for each image that displays randomly using your simple random php script? I appreciate your work in any case.

Thanks again!
Brian

**Comment by jonbellah** [comment]
With the script that I shared, only the selected image will be loaded -- not all 197 at once.
