### ISSUE TITLE
Intro state machines

### ISSUE THREAD

**Issue by pedrofiorito** [jonbellah/jonbellah.com#7]
Hi @jonbellah, I was just reading the JS intro to state machines article (https://jonbellah.com/articles/intro-state-machines/).
Quick heads up, the code pen is referencing xstate instead of XState on the const variable assigning Machine, making the whole thing fail.
Not really important, but since its a quick fix, I thought I would let you know.

Thanks for the article and keep up the good work.

**Comment by jonbellah** [comment]
Fixed, thanks for the heads up!
