### ISSUE TITLE
When will v2 of your xstate course be released?

### ISSUE THREAD

**Issue by fdjones** [jonbellah/jonbellah.com#8]
Hi, I'm really interested in getting your course but I've seen you're working on a v2 for it, so I was just wondering how far away that is from being completed?

Cheers :)

**Comment by martijnsenden** [comment]
> Hi, I'm really interested in getting your course but I've seen you're working on a v2 for it, so I was just wondering how far away that is from being completed?
> 
> Cheers :)

I was just watching the course and was wondering the same thing. It feels outdated and incomplete at the moment. Any estimate on when you'll be able to publish the new material?

**Comment by jonbellah** [comment]
Hey @fdjones and @martijnsenden,

Sorry for the slow reply, have been working on getting a new course platform out the door (which I did just last night!). 

v2 of the course has been written, but I'm waiting on the release of XState v5 before recording. It's a completely rewritten course (materials and associated app)... no longer using `react-automata`, now using Hooks, added a module on TypeScript, added coverage of the Actor model, and a whole lot of other things.

**Comment by fdjones** [comment]
Ah right, that makes sense @jonbellah, cheers for the update :)
